#!/usr/bin/env tsx
/**
 * drift-check.ts -- Detect prose/YAML disagreement in an adversary review.
 *
 * Usage:
 *   drift-check.ts --review <path.md>
 *
 * Adversary reviews emit two outputs in a single model call: a prose
 * summary (for humans) and a fenced ```adversary-review``` YAML block
 * (machine-parsed source of truth). The two can drift -- e.g. YAML
 * lists a `category: security` finding while prose ### Security still
 * says "No issues found". The parser only reads YAML, so this drift
 * never surfaces downstream.
 *
 * This helper re-parses the review file, derives the prose sections
 * each YAML category MUST appear in (see the mapping table in
 * skills/adversary/SKILL.md `## Output Format`), and appends a clearly
 * labelled `## Pipeline Drift Warning` block to the review file if any
 * expected section still uses "no issues" / "none" boilerplate without
 * an F<id> reference.
 *
 * The validator only ANNOTATES. It never edits the prose sections or
 * the YAML block in place; the YAML remains authoritative. Exits 0 in
 * all cases (informational, never blocks the pipeline).
 */

import { readFileSync, appendFileSync } from "fs";
import { parseAdversaryReview, Category } from "../../extensions/lib/adversary-parse";

function getArg(name: string, required: boolean = false): string | undefined {
  const argv = process.argv;
  const idx = argv.indexOf(`--${name}`);
  if (idx >= 0 && idx + 1 < argv.length) return argv[idx + 1];
  if (required) {
    console.error(`ERROR: --${name} is required`);
    process.exit(2);
  }
  return undefined;
}

// Mirrors the "Category → prose section mapping" table in
// skills/adversary/SKILL.md `## Output Format`. Keep the two in lockstep.
const CATEGORY_TO_SECTION: Record<Category, string> = {
  "security":        "Security",
  "race-condition":  "Operational Robustness",
  "error-handling":  "Operational Robustness",
  "resource-leak":   "Operational Robustness",
  "correctness":     "Operational Robustness",
  "performance":     "Complexity Audit",
  "maintainability": "Complexity Audit",
  "idiom":           "Complexity Audit",
};

const BOILERPLATE_RE = /^\s*(no\s+(issues|concerns|findings)|none\b|all\s+claims\s+verified)/im;
const FINDING_REF_RE = /\bF\d+\b/;

/**
 * Slice the body of a prose `### <name>` section out of the review file.
 * Section runs until the next `###`/`##`/`#` header or the opening of
 * the fenced YAML block. Returns null if the section header isn't found.
 */
function extractSectionBody(review: string, name: string): string | null {
  const headerRe = new RegExp(`^###\\s+${name}\\s*$`, "m");
  const m = review.match(headerRe);
  if (!m) return null;
  const start = m.index! + m[0].length;
  const rest = review.slice(start);
  const endMatch = rest.match(/^(##+\s|```)/m);
  const end = endMatch ? endMatch.index! : rest.length;
  return rest.slice(0, end).trim();
}

const reviewPath = getArg("review", true)!;
const raw = readFileSync(reviewPath, "utf8");

const parseResult = parseAdversaryReview(raw);
if (!parseResult.ok || !parseResult.review) {
  // Parse failures are handled by the capture pipeline; nothing for us
  // to validate against. Exit cleanly so we don't poison the artifact.
  process.exit(0);
}

const findingsByCategory = new Map<Category, string[]>();
for (const f of parseResult.review.findings) {
  const ids = findingsByCategory.get(f.category) ?? [];
  ids.push(f.id);
  findingsByCategory.set(f.category, ids);
}

type Drift = { section: string; categories: Category[]; ids: string[]; snippet: string };
const driftsBySection = new Map<string, Drift>();

for (const [category, ids] of findingsByCategory) {
  const section = CATEGORY_TO_SECTION[category];
  if (!section) continue;
  const body = extractSectionBody(raw, section);
  if (body === null) continue; // section absent: can't claim drift
  const isBoilerplate = BOILERPLATE_RE.test(body);
  const referencesFinding = FINDING_REF_RE.test(body);
  if (isBoilerplate && !referencesFinding) {
    const snippet = body.split("\n")[0].slice(0, 80);
    const existing = driftsBySection.get(section);
    if (existing) {
      existing.categories.push(category);
      existing.ids.push(...ids);
    } else {
      driftsBySection.set(section, { section, categories: [category], ids: [...ids], snippet });
    }
  }
}

if (driftsBySection.size === 0) {
  process.exit(0);
}

const lines: string[] = [
  "",
  "---",
  "",
  "## Pipeline Drift Warning",
  "",
  "The YAML `adversary-review` block (authoritative) lists findings whose",
  "matching prose section still uses \"no issues\" / \"none\" boilerplate.",
  "Trust the YAML. Generated by tools/ts/drift-check.ts.",
  "",
];
for (const d of driftsBySection.values()) {
  const cats = Array.from(new Set(d.categories)).join(", ");
  const ids = Array.from(new Set(d.ids)).join(", ");
  lines.push(`- ### ${d.section}: YAML has ${ids} (category: ${cats}) — prose says "${d.snippet}"`);
}
lines.push("");

appendFileSync(reviewPath, lines.join("\n"));
console.error(`drift-check: ${driftsBySection.size} prose section(s) disagree with YAML — see ${reviewPath}`);
process.exit(0);
